version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: pg-lock-lab
    environment:
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab123
      POSTGRES_DB: lock_lab
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - "postgres"
      - "-c"
      - "log_lock_waits=on"
      - "-c"
      - "deadlock_timeout=1s"
      - "-c"
      - "log_statement=all"